version: '3.5'

services:
  gunicorn:
    build: 後端/
    volumes:
      - ./好的/:/opt/好的/:ro
    networks:
      - default
      - nginx-bridge
    environment:
      VIRTUAL_HOST: "dbkaxabu.xn--v0qr21b.xn--kpry57d"
      LETSENCRYPT_HOST: "dbkaxabu.xn--v0qr21b.xn--kpry57d"
      LETSENCRYPT_EMAIL: "ithuan@xn--v0qr21b.xn--kpry57d"
    restart: always

networks:
  nginx-bridge:
    external: true

